---
title: "final_temp"
author: "Mengyu Zhang"
date: "12/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(randomForest)
library(e1071)
library(caret)
library(car)
library(lubridate)

```


```{r}
#Load Data
training <- read.csv("training.csv")
test <- read.csv("test.csv")
```

```{r}
#Feature Engineering 
PublishDate <- c(training$PublishedDate, test$PublishedDate)
date <- PublishDate %>% str_extract("(.*)(?=\\/)") %>% as.Date(format="%m/%d")
wkds <- weekdays(date)
wkds <- as.factor(wkds)
hrs <- PublishDate %>% 
  str_extract("(?<=\\s)(.*)(?=:)") %>% 
  as.factor()
hrs<- ordered(hrs, levels=c("0", "1", "2", "3", "4", "5", "6", "7", "8", 
                            "9", "10", "11", "12", "13", "14", "15", "16", 
                            "17", "18", "19", "20", "21", "22", "23"))
mins <- PublishDate %>% 
  str_extract("(?<=:)(.*)")
mins <- ifelse(mins=="00", "60", mins)
mins <- as.integer(mins)
mins <- cut(mins, breaks=c(0, 10, 20, 30, 40, 50, 60))
##provide graphs
training$wkds <- wkds[1:7242]
training$hrs <- hrs[1:7242]
training$mins <- mins[1:7242]
par(mfrow=c(1, 2))
ggplot(training, aes(x=hrs, y=growth_2_6)) +
  geom_boxplot(fill=rainbow(24)) +
  labs(x="Hours in a Day", y="growth_2_6")
ggplot(training, aes(x=wkds, y=growth_2_6)) +
  geom_boxplot(fill=rainbow(7)) +
  labs(x="Days in a Week", y="growth_2_6")
ggplot(training, aes(x=mins, y=growth_2_6)) +
  geom_boxplot(fill=rainbow(6)) +
  labs(x="Minutes in an Hour", y="growth_2_6")
```

```{r}

#subset data
subdata <- training[, 3:259]

#remove 0 vars
subdata <- subdata[, -nearZeroVar(subdata)]

#remove high correlated r.v's
subdata <- subdata[, -findCorrelation(cor(subdata), cutoff=.9)]

#Transform categorical
for (i in 141:151) {
  subdata[, i] <- as.factor(subdata[, i])
  
}
subdata$growth_2_6 <- training$growth_2_6
subdata$hrs <- training$hrs
subdata$wkds <- training$wkds
subdata$mins <- training$mins
```


```{r}
#Feature Importance
set.seed(123)
recommended.mtry <- floor(sqrt(ncol(subdata)))
rf.imp <- randomForest(growth_2_6~., subdata, mtry=154, ntree=1500)
imp <- importance(rf.imp, scale=F, type=1)
imp.ordered <- imp[order(abs(imp), decreasing=T),]
selected <- c(names(imp.ordered[1:30]), "growth_2_6")
subdata2 <- subdata[, which(colnames(subdata)%in%selected)]

```

```{r}
#fit model
rf <- randomForest(growth_2_6~., subdata2, importance=F, mtry=30, ntree=1500,
                   trControl=oob_train_control)


#Convert test data
test$wkds <- wkds[7243:10347]
test$hrs <- hrs[7243:10347]
test$mins <- mins[7243:10347]
for (i in 248:259) {
  test[, i] <- as.factor(test[, i])
}
pred <- predict(rf, newdata=test)
submit <- data.frame(id=test$id, growth_2_6=pred)
write.csv(submit, file="submit.csv", row.names = F)
```




